version: '2.3'

networks:
    zookeeper-net:
        ipam:
            config:
                - subnet: 172.168.1.0/24
        external: false

services:
    zookeeper_1:
        image: zookeeper:latest
        container_name: zookeeper_cluster_1
        volumes:
            - ./config/zoo1:/conf
            - ./data/zoo1:/data
        networks:
            zookeeper-net:
                ipv4_address: 172.168.1.2
        depends_on:
            - loadbalancer
    zookeeper_2:
        image: zookeeper:latest
        container_name: zookeeper_cluster_2
        volumes:
            - ./config/zoo2:/conf
            - ./data/zoo2:/data
        networks:
            zookeeper-net:
                ipv4_address: 172.168.1.3
        depends_on:
            - loadbalancer
    zookeeper_3:
        image: zookeeper:latest
        container_name: zookeeper_cluster_3
        volumes:
            - ./config/zoo3:/conf
            - ./data/zoo3:/data
        networks:
            zookeeper-net:
                ipv4_address: 172.168.1.4
        depends_on:
            - loadbalancer
    loadbalancer:
        image: haproxy:latest
        container_name: zookeeper-haproxy
        volumes:
            - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        networks:
            zookeeper-net:
                ipv4_address: 172.168.1.5
        ports:
            - 2181:2181
            - 2182:2182
