version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "18123:8123"
      - "19000:9000"
    volumes:
      - ./logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=quasar
      - CLICKHOUSE_PASSWORD=123456
      - CLICKHOUSE_DB=default