version: '3'

services:
  prometheus:
    image:  bitnami/prometheus:2.50.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
  grafana:
    image: grafana/grafana:10.0.12
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus