version: '3'

services:
    mongo:
        image: mongo:6.0.5
        container_name: 'mongo'
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=123456
