version: '3.0'

services:
    zipkin-server:
        image: openzipkin/zipkin:latest
        container_name: zipkin-server
        volumes:
            - ./logs/zipkin:/logs
        ports:
            - 9411:9411
        environment:
            - KAFKA_BOOTSTRAP_SERVERS=kafka.internal:9092
            - KAFKA_TOPIC=zipkin
            - STORAGE_TYPE=kafka
