version: '2.3'

networks:
  redis_net:
    ipam:
      config:
        - subnet: 172.168.2.0/24
    external: false

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    # environment:
    # - REDIS_PASSWORD=123456
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./logs:/var/log/redis
    networks:
      redis_net:
        ipv4_address: 172.168.2.2
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:172.168.2.2:6379
    ports:
      - 16379:8081
    networks:
      redis_net:
        ipv4_address: 172.168.2.3
    depends_on:
      - redis