version: '2.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    # environment:
      # - REDIS_PASSWORD=123456
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./logs:/var/log/redis