version: '3'

networks:
  elastic-stack-net:
    ipam:
      config:
        - subnet: 192.168.2.0/24
    external: false

services:
    elasticsearch:
        image: elasticsearch:8.7.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
        volumes:
            - ./data/elasticsearch:/usr/share/elasticsearch/data
            - ./config/elasticsearch:/usr/share/elasticsearch/config
            - ./logs/elasticsearch:/usr/share/elasticsearch/logs
        networks:
            elastic-stack-net:
                aliases:
                  - elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        image: kibana:8.7.0
        container_name: kibana
        volumes:
            - ./config/kibana:/usr/share/kibana/config
            - ./logs/kibana:/usr/share/kibana/logs
        network_mode: "bridge"
        networks:
            elastic-stack-net:
                aliases:
                  - kibana
        ports:
            - 5601:5601
