version: '3'

services:
    # minio:
    #   image: quay.io/minio/minio:latest
    #   container_name: minio
    #   volumes:
    #     - ./data:/data
    #   environment:
    #     - MINIO_ROOT_USER=minio
    #     - MINIO_ROOT_PASSWORD=minio123456
    #   command: [ 'minio', 'server', 'start' ]
    #   ports:
    #     - 9000:9000
    #     - 9001:9001
    minio:
        image: bitnami/minio:latest
        container_name: minio
        environment:
            - MINIO_ACCESS_KEY=minio
            - MINIO_SECRET_KEY=minio123456
        volumes:
            - ./data:/data
        command:
            [
                'minio',
                'server',
                'start',
                '--console-address',
                ':9001'
            ]
        ports:
            - 9000:9000
            - 9001:9001
